root = "."
tmp_dir = "tmp"
env_files = [".env"]

[build]
cmd = "go build -o ./tmp/creator-crawler ."
bin = "tmp/creator-crawler"
args_bin = ["serve", "--addr", "localhost:8080"]
include_ext = ["go", "css"]
include_dir = ["internal", "static"]
exclude_dir = ["data", "node_modules", "outputs", "tmp"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
delay = 200
stop_on_error = true

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true

[proxy]
enabled = true
app_port = 8080
proxy_port = 8090
app_start_timeout = 5000
